development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "da0afdc6820a912fb53018abdbc13a0d05c45d2caad9d2add4a91878fcf64d35"
  signature_expiration: 3600 # one hour
